### ISSUE TITLE
Problema com data

### ISSUE THREAD

**Issue by laurencioScript** [juanpireslima/json-differences#1]
Fazendo a comparação com objetos que possui data ele sempre diz que houve diferença na data sendo que estão identificas, talvez seja preciso fazer uma melhor comparação.

`{
  "new": {},
  "deleted": {},
  "updated": {
    "createdAt": {
      "new": "2021-11-03T14:06:27.360Z",
      "old": "2021-11-03T14:06:27.360Z"
    },
    "updatedAt": {
      "new": "2021-11-03T14:09:43.516Z",
      "old": "2021-11-03T14:09:43.516Z"
    },
    "observation": {
      "new": "laurencio22",
      "old": "laurencio2"
    },
    "startStoppingTime": {
      "new": "2021-11-03T13:00:00.000Z",
      "old": "2021-11-03T13:00:00.000Z"
    }
  }
}`

**Comment by juanpireslima** [comment]
Problema estava ocorrendo devido á comparação entre objetos, ajuste realizado na versão 1.0.4

**Comment by juanpireslima** [comment]
![image](https://user-images.githubusercontent.com/66164779/140623055-9561a806-841d-45a5-a739-33c8642110ba.png)
